Create ContactList component
BrennDev/contacts-react pull request #4
Opened 2024-09-10 20:50 UTC by Tecuani1

**Creación del componente ContactList:**

- Se creó un componente de clase que se encarga de obtener una lista de usuarios desde una API externa.

- Utiliza componentDidMount para realizar una solicitud fetch a la URL proporcionada como prop (apiUrl).

- Los datos obtenidos se almacenan en el estado del componente y se utilizan para generar una tabla que muestra información del usuario: nombre, email, compañía y título de trabajo.

- Si el usuario tiene un avatar, este se muestra; en caso contrario, se muestra el nombre completo del usuario.

**Creación de filas dinámicas:**

- Se añadió la función createUserRow para generar dinámicamente filas de usuarios basadas en los datos obtenidos.

- Cada fila incluye una imagen de avatar (si está disponible), nombre completo, email, compañía y título de trabajo.

- Validación de propTypes:

- Se incluyó validación de las propTypes para garantizar que la apiUrl recibida sea una cadena requerida.

**Integración con la aplicación principal (App):**

- Se creó un componente App que renderiza ContactList, pasándole la URL de la API (https://reqres.in/api/users?delay=4) como prop.

**Estilos:**

- Se incluyó un archivo CSS ContactList.css para dar estilo a los elementos de la tabla, como los avatares y las celdas.
![image](https://github.com/user-attachments/assets/387f3c41-e89b-468f-b753-9c110ab3461a)

2024-09-11 14:48 UTC, josuemonroy2023 requested changes

2024-09-11 21:35 UTC, Tecuani1 commented on src/components/ContactList.jsx
> +  apiUrl: PropTypes.string.isRequired,
**algo como esto estaria mejor ?** 
```
ContactList.propTypes = {
  users: PropTypes.arrayOf(
    PropTypes.shape({
      first_name: PropTypes.string.isRequired,
      last_name: PropTypes.string.isRequired,
      email: PropTypes.string.isRequired,
      avatar: PropTypes.string,
      company: PropTypes.string,
      job_title: PropTypes.string,
    })
  ).isRequired,
};
```

2024-09-11 21:37 UTC, Tecuani1 commented on src/components/ContactList.jsx
> +    fetch(apiUrl)
decidí crear un archivo externo con el metodo Get para obtener los datos de la api 
```
// Getcontact.js
export const fetchUsers = () => {
  const apiUrl = "https://reqres.in/api/users?delay=4";

  return fetch(apiUrl)
    .then((res) => {
      if (!res.ok) {
        throw new Error(`Error HTTP! Status: ${res.status}`);
      }
      return res.json();
    })
    .then((data) => {
      return data.data;
    })
    .catch((error) => {
      console.error("Error fetching users:", error);
      return [];
    });
};
```

2024-09-11 21:39 UTC, Tecuani1 commented on src/App.jsx
>  function App() {
**Quedaria de la siguiente manera** 
```
import React, { Component } from 'react';
import ContactList from './components/ContactList';
import { fetchUsers } from './Getcontact';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      contacts: [],
    };
  }

  componentDidMount() {
    fetchUsers().then((users) => {
      this.setState({ contacts: users });
    });
  }

  render() {
    const { contacts } = this.state;

    return (
      <div className="App">
        <ContactList users={contacts} />
      </div>
    );
  }
}

export default App;

```

2024-09-11 22:08 UTC, josuemonroy2023 commented on src/components/ContactList.jsx
> +    fetch(apiUrl)
El nombre del archivo debería de estar con camel case `getContacts.js` (los componentes sí deben de ir en Pascal Case, esto es por convención)

2024-09-11 22:37 UTC, josuemonroy2023 requested changes

2024-09-11 22:37 UTC, josuemonroy2023 commented on src/.prettierrc
> +{
Éste archivo debería de estar a la altura del root del proyecto.

2024-09-11 22:37 UTC, josuemonroy2023 commented on src/components/ContactList.jsx
> +    const { users } = this.props;
Pero ahora la referencia sería de `contacts` no de `users`

2024-09-12 20:49 UTC, josuemonroy2023 approved these changes

2024-09-12 20:51 UTC, merged