Initial circle
BrennDev/contacts-react pull request #8
Opened 2024-09-13 22:33 UTC by Tecuani1

**Detalles del Componente:**

- Función getRandomColor: Esta función genera un color hexadecimal aleatorio que se utiliza como color de fondo para el círculo.

**Clase InitialCircle:**

- Estado backgroundColor: Se inicializa en el constructor y se actualiza cuando el componente se monta, utilizando la función getRandomColor.

- Prop firstName: Se toma la primera letra del nombre proporcionado, que se muestra dentro del círculo.

- Estilos: El componente tiene una clase CSS (initial-circle) que le da forma circular, centrado del texto y ajuste de tamaño según las variables CSS definidas.

**Cambios en el Estilo:**

- Se añaden estilos compartidos entre .avatar-img y .initial-circle para garantizar consistencia en el diseño visual (tamaño, bordes, márgenes).

- La clase .initial-circle añade un fondo con el color generado y ajusta el tamaño de la letra para que se centre correctamente en el círculo.

https://github.com/user-attachments/assets/6946e63a-6e3c-49c7-93ef-da9137cadbd2

2024-09-13 22:59 UTC, josuemonroy2023 requested changes

2024-09-13 22:59 UTC, josuemonroy2023 commented on src/components/ContactList.css
> +  display: flex;
Hay que ordenar estas propiedades.

2024-09-13 22:59 UTC, josuemonroy2023 commented on src/components/ContactList.css
> +  display: flex;
Y también de las otras clases.

2024-09-13 22:59 UTC, josuemonroy2023 commented on src/components/InitialCircle.jsx
> +  for (let i = 0; i < 6; i++) {
Sólo para hacer un ejercicio mental. Cómo sería una mejor forma de hacer esta función?
Sobre todo para que no se tenga que concatenar una cadena con el operador "+". Y tal vez sea más clara la intención.

2024-09-17 19:12 UTC, Tecuani1 commented on src/components/ContactList.css
> +  display: flex;
las propiedades ya fueron ordenadas, con excepcion de las de Loadingspinner ya que al ordenar de manera ascendente afectaba la funcionalidad del spinner provocando que no apareciera, por lo cual lo dejamos de esta manera:
```
.spinner {
  width: 48px;
  height: 48px;
  border: 6px solid transparent;
  animation: spin 2s infinite linear;
  border-bottom: 6px solid #1a73e8;
  border-radius: 50%;
  margin: 40px 0 20px 0;
}
```

2024-09-17 19:54 UTC, josuemonroy2023 commented on src/components/ContactList.css
> +  display: flex;
Eso está raro, no debería. Qué pasa si cambias el orden?

2024-09-17 19:57 UTC, josuemonroy2023 commented on src/components/InitialCircle.jsx
> +  for (let i = 0; i < 6; i++) {
Sí vi esta forma. No está mal. Pero en slack comentaba que si aún podría haber algo mejor que hacer.
Pudiste revisarlo?

2024-09-17 20:52 UTC, Tecuani1 commented on src/components/ContactList.css
> +  display: flex;
El spinner no aparece 
![image](https://github.com/user-attachments/assets/9743f38e-0a95-418d-9e23-66d6a9b91aa2)

2024-09-17 21:01 UTC, Tecuani1 commented on src/components/InitialCircle.jsx
> +  for (let i = 0; i < 6; i++) {
mmm tal vez podria usar template para evitar laconcatenacion que utilizaba al principio y podria quedar asi : 
import React, { Component } from 'react';

```
const getRandomColor = () => {
  const randomHex = () => Math.floor(Math.random() * 16).toString(16);
  return `#${randomHex()}${randomHex()}${randomHex()}${randomHex()}${randomHex()}${randomHex()}`;
};

class InitialCircle extends Component {
  constructor(props) {
    super(props);
    this.state = {
      backgroundColor: '',
    };
  }

  componentDidMount() {
    this.setState({ backgroundColor: getRandomColor() });
  }

  render() {
    const { firstName } = this.props;
    const { backgroundColor } = this.state;

    return (
      <div className="initial-circle" style={{ backgroundColor }}>
        {firstName?.charAt(0).toUpperCase() || ''}
      </div>
    );
  }
}

export default InitialCircle;
```

2024-09-17 21:08 UTC, josuemonroy2023 commented on src/components/ContactList.css
> +  display: flex;
Ya entendí qué pasa. El problema es que están usando la misma propiedad de `border` dos veces. Entonces, cuando cambia el orden están sobre escribiéndola. 
Cuando pone `border-bottom` arriba de `border` lo que pasa es que los lee en secuencia y toma la segunda instancia. Entonces sería mejor que se divida, de tal forma que sólo tenga una sóla regla.
 @BrennDev creo que también necesitas saber de esto.

2024-09-17 21:09 UTC, josuemonroy2023 commented on src/components/InitialCircle.jsx
> +  for (let i = 0; i < 6; i++) {
Mmhhh, nope. No te preocupes, mañana lo vemos. La segunda forma que hiciste está bien. Pero sirve cómo ejercicio mental.

2024-09-17 21:10 UTC, BrennDev commented on src/components/ContactList.css
> +  display: flex;
si, estoy al pendiente de los comentarios. Gracia por avisar!

2024-09-17 21:23 UTC, Tecuani1 commented on src/components/ContactList.css
> +  display: flex;
entonces esto podria quedar asi?: 
```
.spinner {
  animation: spin 2s infinite linear;
  border-radius: 50%;
  border-width: 6px;
  border-style: solid;
  border-color: transparent;
  border-bottom-color: #1a73e8;
  height: 48px;
  margin: 40px 0 20px 0;
  width: 48px;
}
```

2024-09-17 21:42 UTC, josuemonroy2023 commented on src/components/ContactList.css
> +  display: flex;
A simple vista... no sé jejeje. No lo veo ordenado, y no sé si te funcionó así.... mi única pregunta sería si no entra en conflicto el border-color general con el específico border-bottom-color. Habría que probar esa parte.

2024-09-17 22:40 UTC, Tecuani1 commented on src/components/ContactList.css
> +  display: flex;
Ya revisé y solo queda de esta manera :( Ayudaaa y ya verifique y border-bottom-color solo se utiliza en esta parte del codigo, no hay nada que interfiera :(
```
.spinner {
  animation: spin 2s infinite linear;
  border-bottom-color: #1a73e8;
  border-radius: 50%;
  border: 6px solid transparent;
  height: 48px;
  margin: 40px 0 20px 0;
  width: 48px;
}
```

2024-09-17 23:24 UTC, josuemonroy2023 commented on src/components/ContactList.css
> +  display: flex;
La cosa es que `border` abarca más propiedades, por eso se puede sobre escribir. Si quieres ya mañana lo vemos con calma en la reunión. Pero puedes ir leyendo sobre cómo funciona el border y cuál es el orden de ejecución de los CSSs.

2024-09-17 23:46 UTC, Tecuani1 commented on src/components/ContactList.css
> +  display: flex;
de acuerdo, sigo investigando...

2024-09-18 15:53 UTC, josuemonroy2023 approved these changes

2024-09-18 17:28 UTC, daini-rl approved these changes

2024-09-18 17:29 UTC, merged